# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Aditya Ganeshan
tagline:          'Music and Maths enthusiast'
description:      Music and Maths enthusiast fiddling with research
url:              http://adityaganeshan.github.io
baseurl:          /

author:
  name:           'Aditya Ganeshan'
  url:            https://twitter.com/SoRapterPhilo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/BardOfCodes

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
